### ISSUE TITLE
Stream OpenAI response to backend + stream to frontend

### ISSUE THREAD

**Issue by Andrewwango** [Andrewwango/govuk-accessible-search#48]
So user gets quick progress

**Comment by olliestanley** [comment]
Relevant: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb

**Comment by olliestanley** [comment]
Turns out Azure Functions in Python actually don't support streaming responses so we can't do this at the moment

**Comment by Andrewwango** [comment]
Removing low-priority as this would be very nice
