### ISSUE TITLE
Issue coming up with a sample query on COVID-19 symptoms page

### ISSUE THREAD

**Issue by Andrewwango** [Andrewwango/govuk-accessible-search#72]
@olliestanley two issues when testing the query _"How long does my cough need to be?"_ on the COVID-19 symptoms page.

- It detected "Treatments" page when the answer is clearly on the symptoms page. I guess that's because the cough might not necessarily be connected to "Symptoms"? Maybe we should actually pass the current page HTML/or a summary of it to the "select relevant section" too?
- Because the answer isn't on Treatments (understandably) it outputted _"I'm sorry, the CONTEXT does not provide information to answer the QUERY."_

**Comment by olliestanley** [comment]
The second issue we probably just need to make it respond in slightly more sensible ways (as in no all caps names)

**Comment by Andrewwango** [comment]
@olliestanley this seems to have been fixed by #81 despite not passing the context from the frontend, do you think it's still worth passing the context in from the frontend?

**Comment by olliestanley** [comment]
> @olliestanley this seems to have been fixed by #81 despite not passing the context from the frontend, do you think it's still worth passing the context in from the frontend?

There are probably some cases where having the context will help, even if not this one. No harm in adding it I think
